/* ====================================== SEGURADORA ====================================== */

CREATE TABLE CLIENTE (ID INT IDENTITY(1,1) PRIMARY KEY,
					NOME VARCHAR(50),
					ENDERECO VARCHAR(100));

CREATE TABLE CARRO_APOLICE (ID INT IDENTITY(1,1) PRIMARY KEY,
					MARCA VARCHAR(50));

CREATE TABLE APOLICE (ID INT IDENTITY(1,1) PRIMARY KEY,
					VALOR INT,
					CLIENTEID INT FOREIGN KEY REFERENCES CLIENTE(ID),
					CARROID INT FOREIGN KEY REFERENCES CARRO_APOLICE(ID));

CREATE TABLE ACIDENTE (ID INT IDENTITY(1,1) PRIMARY KEY,
					DATAHORA DATETIME,
					LOCAL VARCHAR(100),
					CARROID INT FOREIGN KEY REFERENCES CARRO_APOLICE(ID));

DROP TABLE ACIDENTE;
DROP TABLE APOLICE;
DROP TABLE CARRO_APOLICE;
DROP TABLE CLIENTE;

/* ====================================== GERDAU ====================================== */

CREATE TABLE DEPOSITO (ID INT IDENTITY(1,1) PRIMARY KEY,
					NOME VARCHAR(50),
					ENDERECO VARCHAR(100));

CREATE TABLE DEPARTAMENTO (ID INT IDENTITY(1,1) PRIMARY KEY,
					SETOR VARCHAR(50));

CREATE TABLE FUNCIONARIO (ID INT IDENTITY(1,1) PRIMARY KEY,
					SALARIO INT,
					NOME VARCHAR(50),
					TELEFONE VARCHAR(11),
					DEPARTAMENTOID INT FOREIGN KEY REFERENCES DEPARTAMENTO(ID));

CREATE TABLE PROJETO (ID INT IDENTITY(1,1) PRIMARY KEY,
					NOME VARCHAR(50),
					ORCAMENTO INT,
					DATAINICIO DATETIME);

CREATE TABLE PECA (ID INT IDENTITY(1,1) PRIMARY KEY,
					PESO INT,
					COR VARCHAR(20),
					DEPOSITOID INT FOREIGN KEY REFERENCES DEPOSITO(ID));

CREATE TABLE FORNECEDOR (ID INT IDENTITY(1,1) PRIMARY KEY,
					NOME VARCHAR(50),
					ENDERECO VARCHAR(100));

CREATE TABLE PECA_FORNECEDOR (ID INT IDENTITY(1,1) PRIMARY KEY,
					PECAID INT FOREIGN KEY REFERENCES PECA(ID),
					FORNECEDORID INT FOREIGN KEY REFERENCES FORNECEDOR(ID));

CREATE TABLE PROJETO_FORNECEDOR (ID INT IDENTITY(1,1) PRIMARY KEY,
					PROJETOID INT FOREIGN KEY REFERENCES PROJETO(ID),
					FORNECEDORID INT FOREIGN KEY REFERENCES FORNECEDOR(ID));

CREATE TABLE PROJETO_PECA (ID INT IDENTITY(1,1) PRIMARY KEY,
					PECAID INT FOREIGN KEY REFERENCES PECA(ID),
					PROJETOID INT FOREIGN KEY REFERENCES PROJETO(ID));

CREATE TABLE PROJETO_FUNCIONARIO (ID INT IDENTITY(1,1) PRIMARY KEY,
					PROJETOID INT FOREIGN KEY REFERENCES PROJETO(ID),
					FUNCIONARIOID INT FOREIGN KEY REFERENCES FUNCIONARIO(ID),
					HORASTRAB INT);

DROP TABLE PROJETO_FUNCIONARIO;
DROP TABLE PROJETO_PECA;
DROP TABLE PROJETO_FORNECEDOR;
DROP TABLE PECA_FORNECEDOR;
DROP TABLE FORNECEDOR;
DROP TABLE PECA;
DROP TABLE PROJETO;
DROP TABLE FUNCIONARIO;
DROP TABLE DEPARTAMENTO;
DROP TABLE DEPOSITO;

/* ====================================== GVFLIX ====================================== */

CREATE TABLE FILME (ID INT IDENTITY(1,1) PRIMARY KEY,
					NOME VARCHAR(50));

CREATE TABLE ATOR (ID INT IDENTITY(1,1) PRIMARY KEY,
					NOME VARCHAR(50));

CREATE TABLE USUARIO (ID INT IDENTITY(1,1) PRIMARY KEY,
					NOME VARCHAR(50) UNIQUE);

CREATE TABLE FILME_ATORES (ID INT IDENTITY(1,1) PRIMARY KEY,
					FILMEID INT FOREIGN KEY REFERENCES FILME(ID),
					ATORID INT FOREIGN KEY REFERENCES ATOR(ID));

CREATE TABLE FILME_USUARIOS (ID INT IDENTITY(1,1) PRIMARY KEY,
					FILMEID INT FOREIGN KEY REFERENCES FILME(ID),
					USUARIOID INT FOREIGN KEY REFERENCES USUARIO(ID),
					DATAVISTA DATETIME,
					NOTA INT);

DROP TABLE FILME;
DROP TABLE ATOR;
DROP TABLE USUARIO;
DROP TABLE FILME_ATORES;
DROP TABLE FILME_USUARIOS;