DBCC CHECKIDENT ('FORNECEDOR', RESEED, 0);
DBCC CHECKIDENT ('DEPARTAMENTO', RESEED, 0);
DBCC CHECKIDENT ('DEPOSITO', RESEED, 0);
DBCC CHECKIDENT ('FUNCIONARIO', RESEED, 0);
DBCC CHECKIDENT ('PECA', RESEED, 0);
DBCC CHECKIDENT ('PROJETO', RESEED, 0);
DBCC CHECKIDENT ('PECA_FORNECEDOR', RESEED, 0);
DBCC CHECKIDENT ('PROJETO_FORNECEDOR', RESEED, 0);
DBCC CHECKIDENT ('PROJETO_PECA', RESEED, 0);

/* INSERÇÃO DE DADOS */

INSERT INTO FORNECEDOR (NOME, ENDERECO)
	VALUES ('FORNECEDOR 1', 'SÃO LEOPOLDO');

INSERT INTO FORNECEDOR (NOME, ENDERECO)
	VALUES ('FORNECEDOR 2', 'SAPUCAIA');

INSERT INTO FORNECEDOR (NOME, ENDERECO)
	VALUES ('FORNECEDOR 3', 'CANOAS');

INSERT INTO FORNECEDOR (NOME, ENDERECO)
	VALUES ('FORNECEDOR 4', 'ESTEIO');


INSERT INTO DEPARTAMENTO (SETOR)
	VALUES ('A');

INSERT INTO DEPARTAMENTO (SETOR)
	VALUES ('B');

INSERT INTO DEPARTAMENTO (SETOR)
	VALUES ('C');

INSERT INTO DEPARTAMENTO (SETOR)
	VALUES ('D');


INSERT INTO DEPOSITO (NOME, ENDERECO)
	VALUES ('DEPOISTO 1', 'BAIRRO 1');

INSERT INTO DEPOSITO (NOME, ENDERECO)
	VALUES ('DEPOISTO 2', 'BAIRRO 2');

INSERT INTO DEPOSITO (NOME, ENDERECO)
	VALUES ('DEPOISTO 3', 'BAIRRO 3');

INSERT INTO DEPOSITO (NOME, ENDERECO)
	VALUES ('DEPOISTO 4', 'BAIRRO 4');


INSERT INTO FUNCIONARIO (SALARIO, NOME, TELEFONE, DEPARTAMENTOID)
	VALUES (1200, 'FUN1', '(51)999-999', 1);

INSERT INTO FUNCIONARIO (SALARIO, NOME, TELEFONE, DEPARTAMENTOID)
	VALUES (1500, 'FUN2', '(51)999-999', 2);

INSERT INTO FUNCIONARIO (SALARIO, NOME, TELEFONE, DEPARTAMENTOID)
	VALUES (700, 'FUN3', '(51)999-999', 3);

INSERT INTO FUNCIONARIO (SALARIO, NOME, TELEFONE, DEPARTAMENTOID)
	VALUES (9000, 'FUN4', '(51)999-999', 4);


INSERT INTO PECA (PESO, COR, DEPOSITOID)
	VALUES (2, 'AZUL', 1);

INSERT INTO PECA (PESO, COR, DEPOSITOID)
	VALUES (4, 'AMARELO', 2);

INSERT INTO PECA (PESO, COR, DEPOSITOID)
	VALUES (1, 'VERMELHO', 3);

INSERT INTO PECA (PESO, COR, DEPOSITOID)
	VALUES (6, 'VERDE', 4);


INSERT INTO PROJETO (NOME, ORCAMENTO, DATAINICIO)
	VALUES ('AREA 1', 50000, CURRENT_TIMESTAMP);

INSERT INTO PROJETO (NOME, ORCAMENTO, DATAINICIO)
	VALUES ('AREA 2', 40000, CURRENT_TIMESTAMP);

INSERT INTO PROJETO (NOME, ORCAMENTO, DATAINICIO)
	VALUES ('AREA 3', 10000, CURRENT_TIMESTAMP);

INSERT INTO PROJETO (NOME, ORCAMENTO, DATAINICIO)
	VALUES ('AREA 4', 750000, CURRENT_TIMESTAMP);


INSERT INTO PECA_FORNECEDOR (PECAID, FORNECEDORID)
	VALUES (1, 1);

INSERT INTO PECA_FORNECEDOR (PECAID, FORNECEDORID)
	VALUES (2, 2);

INSERT INTO PECA_FORNECEDOR (PECAID, FORNECEDORID)
	VALUES (3, 3);

INSERT INTO PECA_FORNECEDOR (PECAID, FORNECEDORID)
	VALUES (4, 4);


INSERT INTO PROJETO_FORNECEDOR (PROJETOID, FORNECEDORID)
	VALUES (1, 1);

INSERT INTO PROJETO_FORNECEDOR (PROJETOID, FORNECEDORID)
	VALUES (2, 2);

INSERT INTO PROJETO_FORNECEDOR (PROJETOID, FORNECEDORID)
	VALUES (3, 3);

INSERT INTO PROJETO_FORNECEDOR (PROJETOID, FORNECEDORID)
	VALUES (4, 4);

INSERT INTO PROJETO_PECA (PECAID, PROJETOID)
	VALUES (1, 1);

INSERT INTO PROJETO_PECA (PECAID, PROJETOID)
	VALUES (2, 2);

INSERT INTO PROJETO_PECA (PECAID, PROJETOID)
	VALUES (3, 3);

INSERT INTO PROJETO_PECA (PECAID, PROJETOID)
	VALUES (4, 4);


INSERT INTO PROJETO_FUNCIONARIO (PROJETOID, FUNCIONARIOID, HORASTRAB)
	VALUES(1, 1, 4);

INSERT INTO PROJETO_FUNCIONARIO (PROJETOID, FUNCIONARIOID, HORASTRAB)
	VALUES(2, 2, 5);

INSERT INTO PROJETO_FUNCIONARIO (PROJETOID, FUNCIONARIOID, HORASTRAB)
	VALUES(3, 3, 2);

INSERT INTO PROJETO_FUNCIONARIO (PROJETOID, FUNCIONARIOID, HORASTRAB)
	VALUES(4, 4, 7);

/* COMANDOS */

SELECT * FROM DEPARTAMENTO;
SELECT * FROM DEPOSITO;
SELECT * FROM FORNECEDOR;
SELECT * FROM FUNCIONARIO;
SELECT * FROM PECA;
SELECT * FROM PROJETO;

SELECT * FROM PECA_FORNECEDOR;
SELECT * FROM PROJETO_FORNECEDOR;
SELECT * FROM PROJETO_PECA;

SELECT FUNCIONARIO.NOME, FUNCIONARIO.SALARIO FROM FUNCIONARIO ORDER BY SALARIO;

SELECT DEPARTAMENTO.SETOR, AVG(FUNCIONARIO.SALARIO) CUSTO 
	FROM FUNCIONARIO
		INNER JOIN DEPARTAMENTO ON DEPARTAMENTO.ID = FUNCIONARIO.DEPARTAMENTOID 
			GROUP BY DEPARTAMENTO.SETOR ORDER BY CUSTO DESC;

SELECT DEPOSITO.NOME, COUNT(PECA.DEPOSITOID) QTDPECA 
	FROM PECA
		INNER JOIN DEPOSITO ON DEPOSITO.ID = PECA.DEPOSITOID 
			GROUP BY DEPOSITO.NOME ORDER BY QTDPECA;

SELECT FUNCIONARIO.NOME, COUNT(PROJETO_FUNCIONARIO.PROJETOID) PROJETOS
	FROM PROJETO_FUNCIONARIO
		INNER JOIN FUNCIONARIO ON FUNCIONARIO.ID = PROJETO_FUNCIONARIO.FUNCIONARIOID 
			GROUP BY FUNCIONARIO.NOME ORDER BY PROJETOS;

SELECT PROJETO.NOME, PROJETO.ORCAMENTO, COUNT(PROJETO_PECA.PECAID) PEÇASUSADAS
	FROM PROJETO
	INNER JOIN PROJETO_PECA ON PROJETO_PECA.PROJETOID = PROJETO.ID 
		GROUP BY PROJETO.NOME, PROJETO.ORCAMENTO ORDER BY ORCAMENTO DESC, PEÇASUSADAS DESC;

SELECT PROJETO.NOME, FORNECEDOR.NOME
	FROM PROJETO_FORNECEDOR
		INNER JOIN PROJETO ON PROJETO.ID = PROJETO_FORNECEDOR.PROJETOID
		INNER JOIN FORNECEDOR ON FORNECEDOR.ID = PROJETO_FORNECEDOR.FORNECEDORID;

SELECT PECA.COR, AVG(PECA.PESO) PESOMEDIO
	FROM PECA GROUP BY COR;

SELECT PROJETO.NOME, PROJETO.ORCAMENTO, AVG(PROJETO_FUNCIONARIO.HORASTRAB) HORASTRAB
	FROM PROJETO
		INNER JOIN PROJETO_FUNCIONARIO ON PROJETO_FUNCIONARIO.PROJETOID = PROJETO.ID GROUP BY NOME, ORCAMENTO;
