/*======================== SEGURADORA ============================= */

/* Primeiro registro */

INSERT INTO CLIENTE (NOME, ENDERECO)
	VALUES('CLIENTE 1', 'ENDERECO');

INSERT INTO CARRO_APOLICE (MARCA)
	VALUES('MARCA 1');

INSERT INTO ACIDENTE (DATAHORA, LOCAL, CARROID)
	VALUES(CURRENT_TIMESTAMP, 'SAPUCAIA', 13);

INSERT INTO APOLICE (VALOR, CLIENTEID, CARROID)
	VALUES(100, 13, 13);

/* Segundo registro */

INSERT INTO CLIENTE (NOME, ENDERECO)
	VALUES('CLIENTE 2', 'ENDERECO 2');

INSERT INTO CARRO_APOLICE (MARCA)
	VALUES('MARCA 2');

INSERT INTO ACIDENTE (DATAHORA, LOCAL, CARROID)
	VALUES(CURRENT_TIMESTAMP, 'SÃO LEOPOLDO', 14);

INSERT INTO APOLICE (VALOR, CLIENTEID, CARROID)
	VALUES(200, 14, 14);

/* Terceiro registro */

INSERT INTO CLIENTE (NOME, ENDERECO)
	VALUES('CLIENTE 3', 'ENDERECO 3');

INSERT INTO CARRO_APOLICE (MARCA)
	VALUES('MARCA 3');

INSERT INTO ACIDENTE (DATAHORA, LOCAL, CARROID)
	VALUES(CURRENT_TIMESTAMP, 'SÃO LEOPOLDO', 15);

INSERT INTO APOLICE (VALOR, CLIENTEID, CARROID)
	VALUES(200, 15, 15);

/* Quarto registro */

INSERT INTO CLIENTE (NOME, ENDERECO)
	VALUES('CLIENTE 4', 'ENDERECO 4');

INSERT INTO CARRO_APOLICE (MARCA)
	VALUES('MARCA 4');

INSERT INTO ACIDENTE (DATAHORA, LOCAL, CARROID)
	VALUES(CURRENT_TIMESTAMP, 'SÃO LEOPOLDO', 16);

INSERT INTO APOLICE (VALOR, CLIENTEID, CARROID)
	VALUES(200, 16, 16);

DELETE FROM CLIENTE;
DELETE FROM CARRO_APOLICE;
DELETE FROM ACIDENTE;
DELETE FROM APOLICE;

/* Buscas */

select * from CLIENTE;
select * from CARRO_APOLICE;

SELECT CLIENTE.NOME, CARRO_APOLICE.MARCA 
	FROM APOLICE 
		INNER JOIN CLIENTE ON CLIENTE.ID = APOLICE.CLIENTEID
		INNER JOIN CARRO_APOLICE ON CARRO_APOLICE.ID = APOLICE.CARROID ORDER BY CLIENTE.NOME;

SELECT CARRO_APOLICE.MARCA, ACIDENTE.DATAHORA, ACIDENTE.LOCAL 
	FROM ACIDENTE
		INNER JOIN CARRO_APOLICE ON CARRO_APOLICE.ID = ACIDENTE.CARROID ORDER BY ACIDENTE.DATAHORA DESC;

SELECT CARRO_APOLICE.MARCA, COUNT(*) ACIDENTES 
	FROM ACIDENTE
		INNER JOIN CARRO_APOLICE ON CARRO_APOLICE.ID = ACIDENTE.CARROID GROUP BY CARRO_APOLICE.MARCA ORDER BY ACIDENTES;

SELECT CLIENTE.NOME, AVG(APOLICE.VALOR) MÉDIA
	FROM APOLICE
		INNER JOIN CLIENTE ON CLIENTE.ID = APOLICE.CLIENTEID GROUP BY NOME;

