/* ================================== CRIAÇÃO TABELAS ===================================== */

CREATE TABLE CARRO (MODELO VARCHAR(50), PORTAS INT, ARCOND BIT);

CREATE TABLE COMPUTADOR (MOBO VARCHAR(50), CPU VARCHAR(50), GPU VARCHAR(50), RAM INT, FONTE VARCHAR(50));

CREATE TABLE CONTABANCARIA (NOME VARCHAR(50), SALDO INT, TIPOCONTA VARCHAR(50));

CREATE TABLE PAIS (NOME VARCHAR(50), POPULACAO INT, LINGUA VARCHAR(50));

CREATE TABLE PESSOA (NOME VARCHAR(50), IDADE INT, NASCIMENTO DATE);

DROP TABLE CARRO;
DROP TABLE COMPUTADOR;
DROP TABLE CONTABANCARIA;
DROP TABLE PAIS;
DROP TABLE PESSOA;

/* ================================== CARRO ===================================== */


INSERT INTO CARRO (MODELO, PORTAS, ARCOND)
	VALUES('MODELO 1', 4, 1);

INSERT INTO CARRO (MODELO, PORTAS, ARCOND)
	VALUES('MODELO 2', 2, 0);

INSERT INTO CARRO (MODELO, PORTAS, ARCOND)
	VALUES('MODELO 3', 2, 0);

INSERT INTO CARRO (MODELO, PORTAS, ARCOND)
	VALUES('MODELO 4', 4, 0);

INSERT INTO CARRO (MODELO, PORTAS, ARCOND)
	VALUES('MODELO 5', 8, 1);

INSERT INTO CARRO (MODELO, PORTAS, ARCOND)
	VALUES('MODELO 6', 2, 1);

ALTER TABLE CARRO
	ADD RODAS INT;

UPDATE CARRO SET ARCOND = 1
	WHERE MODELO = 'MODELO 3';

UPDATE CARRO SET PORTAS = 0
	WHERE MODELO = 'MODELO 6';

UPDATE CARRO SET PORTAS = 6
	WHERE MODELO = 'MODELO 5';

SELECT * FROM CARRO
	WHERE PORTAS > 2;

SELECT MODELO FROM CARRO
	WHERE ARCOND = 1;

DELETE FROM CARRO;

/* ================================== COMPUTADOR ===================================== */

INSERT INTO COMPUTADOR (MOBO, CPU, GPU, RAM, FONTE)
	VALUES('MB 1', 'I5', 'GTX 999', 8, '999W');

INSERT INTO COMPUTADOR (MOBO, CPU, GPU, RAM, FONTE)
	VALUES('MB 2', 'I3', 'GTX 999', 4, '999W');

INSERT INTO COMPUTADOR (MOBO, CPU, GPU, RAM, FONTE)
	VALUES('MB 3', 'I9', 'GTX 999', 16, '999W');

INSERT INTO COMPUTADOR (MOBO, CPU, GPU, RAM, FONTE)
	VALUES('MB 4', 'I99', 'GTX 9999', 120, '999W');

INSERT INTO COMPUTADOR (MOBO, CPU, GPU, RAM, FONTE)
	VALUES('MB 5', 'I3', 'GTX 999', 4, '999W');

INSERT INTO COMPUTADOR (MOBO, CPU, GPU, RAM, FONTE)
	VALUES('MB 6', 'I9', 'GTX 999', 16, '999W');

ALTER TABLE COMPUTADOR
	ADD HDD INT;

UPDATE COMPUTADOR SET RAM = 240
	WHERE MOBO = 'MB 5';

UPDATE COMPUTADOR SET RAM = 8
	WHERE MOBO = 'MB 2';

UPDATE COMPUTADOR SET RAM = 4
	WHERE MOBO = 'MB 1';

SELECT * FROM COMPUTADOR
	WHERE RAM > 4;

SELECT MOBO FROM COMPUTADOR
	WHERE CPU != 'I3';

DELETE FROM COMPUTADOR;

/* ================================== CONTABANCARIA ===================================== */

INSERT INTO CONTABANCARIA (NOME, SALDO, TIPOCONTA)
	VALUES('FULANO', 1200, 'CORRENTE');

INSERT INTO CONTABANCARIA (NOME, SALDO, TIPOCONTA)
	VALUES('BELTRANO', 5000, 'POUPANÇA');

INSERT INTO CONTABANCARIA (NOME, SALDO, TIPOCONTA)
	VALUES('SICLANO', 8000, 'CORRENTE');

INSERT INTO CONTABANCARIA (NOME, SALDO, TIPOCONTA)
	VALUES('POLTRANO', 900, 'CORRENTE');

INSERT INTO CONTABANCARIA (NOME, SALDO, TIPOCONTA)
	VALUES('NELTANO', 54000, 'POUPANÇA');

INSERT INTO CONTABANCARIA (NOME, SALDO, TIPOCONTA)
	VALUES('JOLTANO', 100500, 'CORRENTE');

ALTER TABLE CONTABANCARIA
	ADD ESTADO VARCHAR(2);

UPDATE CONTABANCARIA SET SALDO = 400
	WHERE NOME = 'BELTRANO';

UPDATE CONTABANCARIA SET TIPOCONTA = 'POUPANÇA'
	WHERE NOME = 'JOLTANO';

UPDATE CONTABANCARIA SET TIPOCONTA = 'FECHADA'
	WHERE NOME = 'POLTRANO';

SELECT * FROM CONTABANCARIA
	WHERE SALDO > 3000;

SELECT NOME, SALDO FROM CONTABANCARIA
	WHERE TIPOCONTA = 'POUPANÇA';

DELETE FROM CONTABANCARIA;

/* ================================== PAÍS ===================================== */

INSERT INTO PAIS (NOME, POPULACAO, LINGUA)
	VALUES('BRASIL', 200000000, 'PORTUGUÊS');

INSERT INTO PAIS (NOME, POPULACAO, LINGUA)
	VALUES('ESTADOS UNIDOS', 150000000, 'INGLÊS');

INSERT INTO PAIS (NOME, POPULACAO, LINGUA)
	VALUES('COLOMBIA', 2000000, 'CASTELHANO');

INSERT INTO PAIS (NOME, POPULACAO, LINGUA)
	VALUES('ARGENTINA', 100000000, 'ESPANHOL');

INSERT INTO PAIS (NOME, POPULACAO, LINGUA)
	VALUES('CHILE', 54000000, 'CASTELHANO');

INSERT INTO PAIS (NOME, POPULACAO, LINGUA)
	VALUES('JAPÃO', 80000000, 'JAPONÊS');

ALTER TABLE PAIS
	ADD MOEDA VARCHAR(30);

UPDATE PAIS SET POPULACAO = 6000000
	WHERE NOME = 'COLOMBIA';

UPDATE PAIS SET POPULACAO = 120000000
	WHERE NOME = 'ARGENTINA';

UPDATE PAIS SET POPULACAO = 50000000
	WHERE NOME = 'JAPÃO';

SELECT * FROM PAIS
	WHERE LINGUA = 'CASTELHANO';

SELECT * FROM PAIS
	WHERE POPULACAO > 20000000;

DELETE FROM PAIS;

/* ================================== PESSOA ===================================== */

INSERT INTO PESSOA (NOME, IDADE, NASCIMENTO)
	VALUES('FULANO', 20, 31-10-1999);

INSERT INTO PESSOA (NOME, IDADE, NASCIMENTO)
	VALUES('BELTRANO', 21, 31-10-1998);

INSERT INTO PESSOA (NOME, IDADE, NASCIMENTO)
	VALUES('NELTRANO', 19, 31-10-2000);

INSERT INTO PESSOA (NOME, IDADE, NASCIMENTO)
	VALUES('PELTRANO', 18, 31-10-2001);

INSERT INTO PESSOA (NOME, IDADE, NASCIMENTO)
	VALUES('LETRANO', 17, 31-10-2002);

INSERT INTO PESSOA (NOME, IDADE, NASCIMENTO)
	VALUES('CELTRANO', 22, 31-10-1997);

ALTER TABLE PESSOA
	ADD GENERO CHAR;

UPDATE PESSOA SET NOME = 'SILTRANO'
	WHERE IDADE = 22;

UPDATE PESSOA SET NASCIMENTO = 30-10-1999
	WHERE NASCIMENTO = 31-10-1999;

UPDATE PESSOA SET NOME = 'BOLTRANO'
	WHERE NOME = 'BELTRANO';

SELECT * FROM PESSOA
	WHERE IDADE > 20;

SELECT NOME FROM PESSOA
	WHERE IDADE < 20;

DELETE FROM PESSOA;